version: '2'

volumes:
  fcrepo-ds:
  fcrepo-obj:
  solr:
  redis:
  db:
  zk1:
  zkconf:
  stacks:
  purl:
  dor:
  sdr:

services:
  zookeeper:
    image: zookeeper
    restart: always
    environment:
      - ZOO_MY_ID=1
      - ZOO_SERVERS=server.1=zoo1:2888:3888
    expose:
      - 2181
    volumes:
      - zk1:/data
      - zkconf:/conf

  solr:
    image: solr
    command: solr -c -f -z zookeeper:2181
    environment:
      VIRTUAL_HOST: solr.${VIRTUAL_HOST_DOMAIN}
    depends_on:
      - zookeeper
    expose:
      - 8983
    volumes:
      - solr:/data

  solr_config_loader:
    image: phusion/passenger-ruby24
    command: /app/solr_config_loader/bin/load
    depends_on:
      - solr
    volumes:
      - ./:/app

  fcrepo:
    build: ./fcrepo/
    expose:
      - 8080
    environment:
      VIRTUAL_HOST: fcrepo.${VIRTUAL_HOST_DOMAIN}
    depends_on:
      - karaf
    volumes:
      - fcrepo-obj:/usr/local/fedora/data/datastreamStore
      - fcrepo-ds:/usr/local/fedora/data/objectStore

  db:
    image: postgres
    volumes:
      - db:/var/lib/postgresql/data

  redis:
    image: redis:3
    command: redis-server
    ports:
      - 6379
    volumes:
      - redis:/data

  karaf:
    build: ./karaf/
    environment:
      VIRTUAL_HOST: karaf.${VIRTUAL_HOST_DOMAIN}
      VIRTUAL_PORT: 8181
    entrypoint: /opt/karaf/bin/karaf server
    ports:
      - 8181
      - 61613
      - 61616
    volumes:
      - ./karaf/deploy:/deploy

  suri:
    build: ./suri/
    environment:
      DATABASE_URL: postgres://postgres@db:5432/suri
      VIRTUAL_HOST: suri.${VIRTUAL_HOST_DOMAIN}
    depends_on:
      - db

  # needs db config
  workflow-service:
    build: ./workflow-service/
    environment:
      VIRTUAL_HOST: workflow-service.$VIRTUAL_HOST_DOMAIN
      DATABASE_URL: postgres://postgres@db:5432/workflow-service
    depends_on:
      - db

  # workflow-archiver-service:
  #   build: ./workflow-archiver-service/
  #   depends_on:
  #     - db

  dor-services-app:
    build: ./dor-services-app/
    environment:
      SETTINGS__SOLRIZER_URL: http://solr:8983/solr/argo
      SETTINGS__SURI__URL: http://suri
      SETTINGS__WORKFLOW_URL: http://workflow-service/
      SETTINGS__SDR_URL: http://sdr-services-app/
      SETTINGS__CONTENT__SDR_SERVER_URL: http://sdr-services-app/
      VIRTUAL_HOST: dor-services-app.${VIRTUAL_HOST_DOMAIN}
    depends_on:
      - fcrepo
      - solr
      - suri
      - workflow-service
    volumes:
      - dor:/dor

  # oci8 dependency..
  # sdr-services-app:
  #   build: ./sdr-services-app/
  #   volumes:
  #     - sdr:/sdr

  dor_indexing_app:
    build: ./dor_indexing_app/
    environment:
      SETTINGS__DOR_SERVICES_URL: http://dor-services-app/
      SETTINGS__FEDORA_URL: http://fcrepo/fedora
      SETTINGS__SOLRIZER_URL: http://solr:8983/solr/argo
      SETTINGS__WORKFLOW_URL: http://workflow-service/
      VIRTUAL_HOST: dor_indexing_app.${VIRTUAL_HOST_DOMAIN}
    depends_on:
      - fcrepo
      - solr
      - workflow-service
      - dor-services-app

  argo-app:
    build: ./argo/
    environment:
      DATABASE_URL: postgres://postgres@db:5432/argo
      SOLR_URL: http://solr:8983/solr/argo # TODO
      SETTINGS__DOR_SERVICES_URL:
      SETTINGS__DOR_INDEXING_URL:
      SETTINGS__FEDORA_URL:
      SETTINGS__MODSULATOR_URL:
      SETTINGS__NORMALIZER_URL:
      SETTINGS__PURL_URL:
      SETTINGS__SOLRIZER_URL: http://solr:8983/solr/argo
      SETTINGS__STACKS_FILE_URL:
      SETTINGS__STACKS_URL:
      SETTINGS__WORKFLOW_URL:
      SETTINGS__SURI__URL:

  argo-web:
    extends: argo-app
    depends_on:
      - dor-services-app
      - modsulator-app
      - db
      - suri
    environment:
      VIRTUAL_HOST: argo.${VIRTUAL_HOST_DOMAIN}

  argo-workers:
    extends: argo-app
    command: bundle exec eye load -f config/eye/delayed_job_workers.eye
    depends_on:
      - dor-services-app
      - modsulator-app
      - db

  modsulator-app:
    build: ./modsulator-app/
    environment:
      VIRTUAL_HOST: modsulator-app.${VIRTUAL_HOST_DOMAIN}

  hydrus:
    build: ./hydrus/
    environment:
      DATABASE_URL: postgres://postgres@db:5432/hydrus
      VIRTUAL_HOST: hydrus.${VIRTUAL_HOST_DOMAIN}
      SOLR_URL: http://solr:8983/solr/hydrus
    depends_on:
      - dor-services-app
      - suri
      - db

  # etds:
  #   build: ./etds/
  #   depends_on:
  #     - fcrepo
  #     - solr
  #     - suri
  #     - db

  image-server:
    build: ./image-server/
    environment:
      VIRTUAL_HOST: image-server.${VIRTUAL_HOST_DOMAIN}
    volumes:
      - stacks:/stacks

  stacks:
    build: ./stacks/
    environment:
      SETTINGS__STACKS__STORAGE_ROOT: /stacks
      SETTINGS__PURL__URL: http://purl/
      SETTINGS__CORS__ALLOW_ORIGIN_URL: http://sul-embed.${VIRTUAL_HOST_DOMAIN}/
      SETTINGS__STACKS__REMOTE_IIIF__IMAGE__ATTRIBUTES__BASE_URI: 'http://image-server/iiif/2/'
      SETTINGS__STACKS__REMOTE_IIIF__METADATA__ATTRIBUTES__BASE_URI: 'http://image-server/iiif/2/'
      VIRTUAL_HOST: stacks.${VIRTUAL_HOST_DOMAIN}
    depends_on:
      - purl
      - image-server
    volumes:
      - stacks:/stacks

  purl:
    build: ./purl/
    environment:
      SETTINGS__DOCUMENT_CACHE_ROOT: /purl
      SETTINGS__PURL_RESOURCE__MODS: /purl/%{druid_tree}/mods
      SETTINGS__PURL_RESOURCE__MODS: /purl/%{druid_tree}/public
      SETTINGS__STACKS__URL: http://stacks.${VIRTUAL_HOST_DOMAIN}/
      SETTINGS__EMBED_HOST: http://sul-embed/
      SETTINGS__EMBED__URL: http://sul-embed.${VIRTUAL_HOST_DOMAIN}/%{druid}
      SETTINGS__EMBED__URL_TEMPLATE: http://sul-embed.${VIRTUAL_HOST_DOMAIN}/{?format,url*,application_options*}
      SETTINGS__EMBED__IFRAME__URL_TEMPLATE: http://sul-embed.${VIRTUAL_HOST_DOMAIN}/iframe{?url*}
      VIRTUAL_HOST: purl.${VIRTUAL_HOST_DOMAIN}
    volumes:
      - purl:/purl

  purl-fetcher:
    build: ./purl-fetcher/
    environment:
      DATABASE_URL: postgres://postgres@db:5432/purl-fetcher
      VIRTUAL_HOST: purl-fetcher.${VIRTUAL_HOST_DOMAIN}
    volumes:
      - purl:/purl

  sul-embed:
    build: ./sul-embed
    environment:
      SETTINGS__PURL_URL: http://purl.${VIRTUAL_HOST_DOMAIN}/
      SETTINGS__VALID_PURL_URL: # TODO...
      SETTINGS__STACKS_URL: http://stacks.${VIRTUAL_HOST_DOMAIN}/
      SETTINGS__EMBED_IFRAME_URL: http://sul-embed.${VIRTUAL_HOST_DOMAIN}/iframe
      SETTINGS__GEO_EXTERNAL_URL: # TODO
      SETTINGS__GEO_WMS_URL: # TODO
      SETTINGS__WAS_THUMBS_URL: # TODO
      VIRTUAL_HOST: sul-embed.${VIRTUAL_HOST_DOMAIN}
    depends_on:
      - purl

  discovery-dispatcher:
    build: ./discovery-dispatcher/
    environment:
      DATABASE_URL: postgres://postgres@db:5432/discovery-dispatcher
      VIRTUAL_HOST: discovery-dispatcher.${VIRTUAL_HOST_DOMAIN}
    depends_on:
      - purl-fetcher

  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  # robots:
  #   build: ./robots/
  #   depends_on:
  #     - redis
  #     - fcrepo
  #     - solr
  #     - dor-services-app
  #   volumes:
  #     - dor:/dor
  #     - stacks:/stacks
  #     - purl:/purl
  #
  robot-master:
    build: ./robot-master/
    depends_on:
      - redis
      - workflow-service
  #
  # sdr-preservation-core-robots:
  #   build: ./sdr-preservation-core-robots
  #   volumes:
  #     - sdr:/sdr
  #
  # catalog-service:
  #   build: ./catalog-service
  #
  # preassembly:
  #   build: ./preassembly
